name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - learner

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: chendaniely/ds4biomed
          service-name: gh
          target-state: learner
